### ISSUE TITLE
Error when trying to complete a task

### ISSUE THREAD

**Issue by jason-mehmel** [ransome1/sleek#13]
Discovered an error when I tried to use Sleek today!

I opened sleek, chose my inbox context, and started clicking 'done' on some stuff that I'd already completed. They didn't get removed from the task list. I tried clicking on other, same issue.

I noticed (because I have 'completed todos' selected) that at the bottom of the list, there is a completed task, and it's the same one I clicked on. In fact, it changes based on whichever task I'm clicking 'done' on, but it never takes the actual task into 'done' status. (Does that make sense? It's basically copying the task line and putting it at the end of the file.)

I checked by opening the file in my text editor, and I can see a copy of the same task line with the done 'x' on it. And the same behaviour. Click on a different task to complete, reload the file in the text editor, it's whatever task I've tried to process at the end with an 'x'.

Not sure if anyone else has had this yet, or if it's unique to me.

I'm on Ubuntu 20.04. I've just uninstalled and reinstalled the app through snap.

**Comment by jason-mehmel** [comment]
Oh, also, I noticed that when I tried creating and completing a task within Sleek itself, the process works as it should. So it's only the tasks that are inherited when it opens the file.

I'm spitballing, but could that be a permissions thing?

**Comment by ransome1** [comment]
Hi Jason.

Thanks for the bug report. I tried to reproduce it real quick, but so far didn't succeed. For me the latest revision from Snap (138) works as it should. But your problem sounds familiar, like something I saw during development last month. Though I am sure I fixed it. Nevertheless I will dig into it as soon as I finish the recurring todo feature that is in the pipeline right now.

I will get back to you here as soon as I got the fix.

I'm glad to see you're still using sleek :)

**Comment by jason-mehmel** [comment]
Some more discoveries:

- The 'completed' task behaviour is appended to the end of the text file, but I've also seen it replace a different task if there aren't any lines left 

- Looking on the ubuntu software centre, I'm using 0.6.0, latest/edge

**Comment by jason-mehmel** [comment]
Yet more discoveries (then I'm going to bed)

- I have another todo.txt file I use for testing apps, such as Sleek! None of the problems I've discovered happened there! Which makes me wonder about file permissions? Or if there's some legacy config file that got garbled for a file in my /Dropbox/TODO location that doesn't affect performance when I'm pointing at a todo.txt file somewhere else?

**Comment by ransome1** [comment]
Well, good morning then ;) Here it's already getting dark again.

If the other file would have a permission issue, than writing would propably not be possible at all. But as I understand from your description, sleek actually does write into the file, but in a wrong way, right?

Anyway, I haven't had the time to work on this bug yet, but I just uploaded an alpha release for the recurring todo feature and with it come quite some other optimisiations. Not your issue in particular though. But if you like, you can just install this pre-relase from Snapstore's Edge Channel using `sudo snap install --edge sleek`.

It's a long shot but it would be interesting to know if even the new version will produce the odd behavior you described.

**Comment by jason-mehmel** [comment]
Ha! We must be in totally different time zones. I'm in Western Canada, what general area are you in?

Still the same behaviour...

I wondered if it's a problem with the config area and files somehow... because even when I remove the app entirely it starts in dark mode, so I thought maybe it was inheriting behaviour somehow.

I tried deleting the config folder, in /Home/.config/Sleek. Reinstalled Sleek via a .deb file, same behaviour.

After removing, I saw the Sleek folder inside the Snap Folder, with a file that the file browser defined as 'broken.' I removed Sleek using Snap, reinstalled it, same behaviour.

Are there error logs I can check? Or just logs in general reporting on what the system is doing?

Another thought: could this have anything to do with the fact that other apps touch the file? Could Dropbox be protecting the file somehow? (I've got a browser option I've been working with for a little while, and Simpletask on my phone. I'm just trying to sort out why it seems to be just this file, or just this location.

**Comment by ransome1** [comment]
Berlin, Germany, that's quite some distance ;)

There are no logs written into a file, but you can open the developer tools as this is an Electron app. Sleek has a menu, push the alt key to see it. Under "About" you can toogle the debugging tools. The tab "Console" will show you what sleek does. Any sign of an entry starting with "Error in ..." will help us.

**Comment by jason-mehmel** [comment]
Gutentag! My family is mostly German. I've never been, though I'd love to.

I will check that the debugging tools!

On the off chance... I tried deleting the todo.txt file, creating a new one, and then copy-pasting all of my content into the new file.

Still the same.

Other questions:

Could I be reaching an upper file limit? I've probably got 500 lines in my file, but a lot of those are reference notes.

Could there be a character issue? Something in this file that is causing an error because of a character used or something that is causing Sleek to error out?

The reason I'm going down these roads is because I'm also considering that no one else has reported this so far, and it's also either only this file or only this file location, so what unique qualifier did I bring to this somehow?

**Comment by ransome1** [comment]
Did you use sleek to create the file before copying the content into it?

**Comment by jason-mehmel** [comment]
I did not! I will try that!

**Comment by jason-mehmel** [comment]
Tried it, didn't work.

**Comment by ransome1** [comment]
If you say the file is mostly consisting references, is it possible that there are duplicate entries in that file? So far I have not build in a check for duplicates before saving stuff. So maybe sleek is having problem with completing todos that have a clone.

I'm not aware of a file limit, but must admit that I've never used sleek with such a large file. Is it working well performance wise?

**Comment by jason-mehmel** [comment]
It works well performance wise!

I'm not sure about duplicates... let me see if I can find any and clean that up.

Here's the console from me both trying to complete a task, and then 'uncompleting' that task.

complete

render.js:1430 Success: Changes written to file: /home/jason/Dropbox/TODO/todo.txt
render.js:640 Success: File watcher is watching: /home/jason/Dropbox/TODO/todo.txt
render.js:648 Success: TodoTXT objects created
render.js:1916 Info: Ending onboarding
render.js:1208 Success: All filters have been generated and built
render.js:1210 Filters rendered: 54.565000000351574 ms
render.js:653 Success: Todo data generated and table built
render.js:655 Table rendered in 54.720000000088476 ms
render.js:782 Success: Data has been extracted from file and parsed to todo.txt items

uncomplete:

render.js:1430 Success: Changes written to file: /home/jason/Dropbox/TODO/todo.txt
render.js:640 Success: File watcher is watching: /home/jason/Dropbox/TODO/todo.txt
render.js:648 Success: TodoTXT objects created
render.js:1916 Info: Ending onboarding
render.js:1208 Success: All filters have been generated and built
render.js:1210 Filters rendered: 48.37500000029104 ms
render.js:653 Success: Todo data generated and table built
render.js:655 Table rendered in 48.5049999988405 ms
render.js:782 Success: Data has been extracted from file and parsed to todo.txt items

**Comment by ransome1** [comment]
That looks perfectly fine, sleek is not having problems writing or reading anything from that file.

Can you do me a favor and move that file out of the Dropbox into a place that is not synced by any application? Because maybe Dropbox is doing some temporaral writings into the file for whatever reason. That actually would trigger the file watcher that is implemented in sleek.

If that's not the case it seems to be something in the file. Say, the weird behavior does occur with every todo you complete? Or just with specific ones?

**Comment by ransome1** [comment]
If duplicates are the problem that would be a great finding, as I can implement a function that would remove duplicates automatically. Unless there is a reason, why there should be a todo that is completely identical to another one.

**Comment by jason-mehmel** [comment]
I used Sublime Text 3 to sort for duplicates, as well as a plugin to remove them. I didn't find any but that should have taken care of it.

Still the same!

I also copied to my home folder, out of Dropbox. Still the same! 

So there must be something in this file. Could it be something like a smart-quotes vs straight-quotes issue?

**Comment by ransome1** [comment]
It's possible and I'm really curious what it is. sleek is handling the file using utf-8 which is one of the most common encodings out there, that should handle everything you've written or pasted into the file quite well. But you never know.

Does the file contain sensible or personal data? If not you can send it to me by mail and I'll take a look myself.

**Comment by jason-mehmel** [comment]
Oh, also: When I try to complete a task, it copies the line to the bottom of the .txt file and puts an x after it... but when I go to un complete it, it uncompletes that task and now there are two copies of the task line!

I'll add some screenshots to show the behaviour: You can see my inbox list, then one inbox item 'completed' but also still in the list, and then a duplicate of that item in the list.

![Screenshot from 2021-01-06 10-59-17](https://user-images.githubusercontent.com/3622823/103803820-59b91c80-500e-11eb-9327-22e7255f74f8.png)
![Screenshot from 2021-01-06 10-58-48](https://user-images.githubusercontent.com/3622823/103803824-5a51b300-500e-11eb-9a1b-e9be0b535fa5.png)
![Screenshot from 2021-01-06 10-58-29](https://user-images.githubusercontent.com/3622823/103803825-5a51b300-500e-11eb-9cd4-9659fe8f2376.png)


.

**Comment by jason-mehmel** [comment]
Let me see if there's anything personal in here that I don't feel comfortable sharing!

**Comment by jason-mehmel** [comment]
It's hard to determine what's personal and what's just weird in a file this big! But I think I'm comfortable sending it to you. I'd rather not paste it here, can I email it to you?

**Comment by ransome1** [comment]
Sure of course, just send it to ransome@uber.space

But only if it's really fine with you as this list looks personal.

Quick question about the screenshots. The sorting is upside down right? Or do you have a duplicate entry for "family history interviews" when you start clicking on complete?

**Comment by jason-mehmel** [comment]
Ah yes. They are upside down, sorry. The bottom one shows the 'start' and the middle is after clicking complete, and the top one shows the now-duplicated file.

I don't mind sending it... it is personal but it won't mean much to you, and there's so much there that I don't get the vibe that you'll even want to go through it other than trying to find rogue characters or something.

**Comment by jason-mehmel** [comment]
Sent!

I cleaned up the file by removing a bunch of tasks that were old or that were no longer valid.

I also found a task that had two slashes and modified them to hyphens... still the same behaviour!

**Comment by jason-mehmel** [comment]
I'd love to know if you have the same problem when you load up my file in your own Sleek.

**Comment by ransome1** [comment]
I'm having the same weird behavior. Which is good and bad news at the same time I guess ;)

Tomorrow I will try to find some time to look into it. I'm really curious what the reason is. I'll get back to you as soon as I find something.

**Comment by ransome1** [comment]
Hi @jason-mehmel .

Could you please update sleek from Snaps edge channel and tell me if it working now?

Please backup your todo file before, because it will change.

The problem was that for completing or uncompleting todos, sleek needs to find the right line number to change the todo. Doing so for performance reasons, I am comparing text strings with each other, but sleek could not find a match.

This is because the text lines in your file are not written according to the todo.txt syntax. For instance you're putting contexts first thing after the start date. But the syntax says that you need to append contexts after the text. When reading your todo.txt file, sleek parses the todos according the todo.txt syntax and will therefor rearrange your syntax according to the official one.

Here is an example. In your todo.txt file you have let's say "2021-03-07 @001_inbox TODONAME". When sleek reads the file it will create a valid object that, when converted to a text again for comparison tasks, will be "2020-03-07 TODONAME @001_inbox". Now, when completing a todo, sleek will compare the new string "2020-03-07 TODONAME @001_inbox" with your line in the todo.txt file "2021-03-07 @001_inbox TODONAME" and, of course, will never find it, because the lines are not identical. As a result, the completed todo will be appended at the end of the file and your initial todo will still be at the old position in your file.

But the thing is, as soon as you will do your first edit on your todo.txt file using sleek, it will completely rearrange your lines. According to the official syntax, which is not bad, I would say, but if you have your own system, that will be a problem.

Anyway, please backup and let me know if the problem persists.

**Comment by ransome1** [comment]
PS: That is actually quite a sophisticated bug and I am really glad we found it.

**Comment by jason-mehmel** [comment]
I'm impressed. And this is probably useful not just for this, but for anyone else playing with todo.txt.

I often apply contexts first because my thought process is: "This is going in the Inbox," so that's the first thing I type.

Question: Do I need to change my todo.txt to get in line with 'text-then-context' format, or will this new version adapt to my style?

**Comment by ransome1** [comment]
I'm afraid sleek will not be able to adapt to your style. It will understand it, but as soon, as it saves any change to the file, your style will be replaced by the official one automatically.

You don't need to rewrite your file, because sleek will do this for you as soon as you do your first edit using sleek, like for instance completing a task. This is why you should backup your file, if you're depending on your own style, because that will be gone unfortunatelly.

**Comment by jason-mehmel** [comment]
I'm not picky about the style!

Okay, next question: if I'm creating todo tasks with my other apps (Simpletask on my phone syncing with Dropbox) should I keep the correct style of TASK - CONTEXT when creating tasks there?

(Maybe that's how this bug started, by creating todos on my phone in the wrong style?)

Or will it not matter, as soon as Sleek opens it will rewrite the todo.txt file it will be 'fixed' or otherwise reformatted for correct style?

I guess I'm asking if you've made Sleek bug-proof against this style by Sleek re-writing the file to put all contexts after the task text?

**Comment by ransome1** [comment]
`Or will it not matter, as soon as Sleek opens it will rewrite the todo.txt file it will be 'fixed' or otherwise reformatted for correct style?`

Exactly, you can basically write your todos however you like, it doesn't matter. Also if other apps write the todos not according to the official syntax, it doesn't matter. As soon as sleek opens your file, it will read line by line using a todo.txt parser (of which I am not the author, but it's a great piece of programming) that identifies all todo.txt attributes, like due dates, contexts, projects, priorities and so on and creates proper todo.txt objects. Using these objects, sleek is now able to build the filters, sort todos to the priority groups and so forth. And now, when you save something, sleek will convert all these todo.txt objects back into text strings. But those text strings will now have the official syntax. But I am pretty sure other todo.txt apps should not have any problems with that.

**Comment by ransome1** [comment]
I'm uploading the 0.7.0 to Snap Store right now. This fix is included as is a check for duplicates, when you enter new todos. That has nothing todo with this case, but could become handy.

Also on higher resolutions than 1000px in width, the filter bar will be a bit wider. Because looking at your screenshots and seeing the amount of contexts and projects, it gives me a good idea on how sleek might be really used in the field. I think a bit wider filter bar might be helpful for you. 

If it's fine for you I will close this issue. Looking forward to the next one :+1:
